"""create posts and comments tables

Revision ID: a8f9fb304910
Revises: a1b2c3d4e5f6
Create Date: 2026-05-04 17:25:47.615983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f9fb304910'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('posts_author_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('comments_author_id_fkey')),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('comments_parent_id_fkey')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('comments_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.drop_index(op.f('ticker_idx'), table_name='assets')
    op.create_index(op.f('assets_id_idx'), 'assets', ['id'], unique=False)
    op.create_index(op.f('assets_ticker_idx'), 'assets', ['ticker'], unique=True)
    op.drop_index(op.f('ix_news_article_tickers_ticker'), table_name='news_article_tickers')
    op.drop_index(op.f('price_data_timestamp_idx'), table_name='price_data')
    op.create_index(op.f('price_data_id_idx'), 'price_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('price_data_id_idx'), table_name='price_data')
    op.create_index(op.f('price_data_timestamp_idx'), 'price_data', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_news_article_tickers_ticker'), 'news_article_tickers', ['ticker'], unique=False)
    op.drop_index(op.f('assets_ticker_idx'), table_name='assets')
    op.drop_index(op.f('assets_id_idx'), table_name='assets')
    op.create_index(op.f('ticker_idx'), 'assets', ['ticker'], unique=True)
    op.drop_table('comments')
    op.drop_table('posts')
    # ### end Alembic commands ###
