"""add news_articles news_article_tickers news_article_topics

Revision ID: df6368582bde
Revises: 6b20bf7cc328
Create Date: 2026-03-19 08:29:23.236041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6368582bde'
down_revision: Union[str, Sequence[str], None] = '6b20bf7cc328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('authors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('source_domain', sa.String(length=256), nullable=True),
    sa.Column('primary_topic', sa.String(length=128), nullable=True),
    sa.Column('primary_ticker', sa.String(length=20), nullable=True),
    sa.Column('overall_sentiment_score', sa.Float(), nullable=True),
    sa.Column('overall_sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('news_articles_pkey')),
    sa.UniqueConstraint('url', name=op.f('news_articles_url_key'))
    )
    op.create_index(op.f('news_articles_id_idx'), 'news_articles', ['id'], unique=False)
    op.create_table('news_article_tickers',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], name=op.f('news_article_tickers_article_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('news_article_tickers_pkey')),
    sa.UniqueConstraint('article_id', 'ticker', name='uq_article_ticker')
    )
    op.create_index(op.f('news_article_tickers_id_idx'), 'news_article_tickers', ['id'], unique=False)
    op.create_table('news_article_topics',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], name=op.f('news_article_topics_article_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('news_article_topics_pkey')),
    sa.UniqueConstraint('article_id', 'topic', name='uq_article_topic')
    )
    op.create_index(op.f('news_article_topics_id_idx'), 'news_article_topics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('news_article_topics_id_idx'), table_name='news_article_topics')
    op.drop_table('news_article_topics')
    op.drop_index(op.f('news_article_tickers_id_idx'), table_name='news_article_tickers')
    op.drop_table('news_article_tickers')
    op.drop_index(op.f('news_articles_id_idx'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
