"""Add price data models

Revision ID: f3736648e594
Revises: df6368582bde
Create Date: 2026-03-27 04:26:41.349083

NOTE: The original autogenerated version of this file contained only `pass`
because the tables already existed in the target database at the time it was
generated.  This corrected version creates the tables so that a fresh database
(e.g. a new developer's local environment) migrates cleanly.

TimescaleDB 2.x requires that every unique index (including the primary key)
on a hypertable contains the partitioning column.  Therefore price_data uses a
composite primary key (id, timestamp) here so that the next migration can call
create_hypertable without constraint errors.  SQLAlchemy maps the ORM identity
through the `id` column and operates correctly with a composite PK at the
database level.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f3736648e594'
down_revision: Union[str, Sequence[str], None] = 'df6368582bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- assets -------------------------------------------------
    op.create_table(
        'assets',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('ticker', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=True),
        sa.Column('asset_type', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False,
                  server_default=sa.text('true')),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name='assets_pkey'),
    )
    op.create_index('ticker_idx', 'assets', ['ticker'], unique=True)

    # ---- price_data ---------------------------------------------
    # TimescaleDB 2.x requires the partitioning column (timestamp) to be part
    # of ALL unique constraints, including the primary key.  We therefore use
    # a composite PK (id, timestamp).
    op.create_table(
        'price_data',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('asset_id', sa.UUID(), nullable=False),
        sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('timeframe', sa.String(length=10), nullable=False),
        sa.Column('open', sa.Float(), nullable=False),
        sa.Column('high', sa.Float(), nullable=False),
        sa.Column('low', sa.Float(), nullable=False),
        sa.Column('close', sa.Float(), nullable=False),
        sa.Column('adj_close', sa.Float(), nullable=True),
        sa.Column('volume', sa.Float(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['asset_id'], ['assets.id'],
            name='price_data_asset_id_fkey',
            ondelete='CASCADE',
        ),
        # Composite PK satisfies TimescaleDB's partitioning uniqueness constraint
        sa.PrimaryKeyConstraint('id', 'timestamp', name='price_data_pkey'),
        sa.UniqueConstraint(
            'asset_id', 'timestamp', 'timeframe',
            name='uq_asset_time_frame',
        ),
    )
    op.create_index(
        'ix_price_data_asset_time', 'price_data',
        ['asset_id', 'timestamp'], postgresql_using='btree',
    )


def downgrade() -> None:
    op.drop_index('ix_price_data_asset_time', table_name='price_data')
    op.drop_table('price_data')
    op.drop_index('ticker_idx', table_name='assets')
    op.drop_table('assets')
