/**
 * Renders trusted HTML content from TipTap editor output.
 * Only used for content that was generated by our own RichTextEditor —
 * NOT for arbitrary user-pasted HTML.
 */
interface Props {
  content: string;
  className?: string;
}

export function HtmlRenderer({ content, className = "" }: Props) {
  if (!content || content === "<p></p>") return null;
  return (
    <div
      className={`rich-editor-content ${className}`}
      dangerouslySetInnerHTML={{ __html: content }}
    />
  );
}
